---
volumes:
  postgres-data:

services:
  db:
    container_name: postgresql
    image: "postgres:12.2-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./insights
    ports:
      - "8501:8501"
    depends_on:
      - backend
