name: Database Migration

on:
  workflow_dispatch:
    inputs:
      action:
        description: Synchronize or Rollback
        required: true
        type: choice
        options:
          - "Synchronize"
          - "Rollback"
        default: "Synchronize"

    dry_run:
      type: choice
      description: Dry Run
      options:
        - "true"
        - "false"
      default: "true"

jobs:
  synchronize:
    runs-on: self-hosted

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get install -y libpq-dev
          python -m pip install --upgrade pip
          pip install psycopg2 argparse

      - name: DB Synchronization
        if: github.event_name == 'workflow_dispatch' && inputs.dry_run == 'false' && inputs.action != 'rollback'
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python db/db_migrate.py --up

      - name: DB Rollback
        if: github.event_name == 'workflow_dispatch' && inputs.dry_run == 'false' && inputs.action != 'synchronize'
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python db/db_migrate.py --down
