name: Python Lint

on:
  push:
    branches: [main, stg, dev]
  pull_request:
    types: [opened, synchronize]
    branches: [main, stg, dev]
    paths:
      - "**.py"

jobs:
  data-loader-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Black
        uses: psf/black@stable
        with:
          src: "./components/data_loader"
          options: "--check --verbose"
          version: "24.2.0"

      - name: Install dependencies
        run: pip install pylint

      - name: Run Pylint
        run: pylint --rcfile=.pylintrc .
