name: SQL Lint using SQLFluff

on:
  push:
    branches: [main, stg, dev]
  pull_request:
    types: [opened, synchronize]
    branches: [main, stg, dev]
    paths:
      - "**.sql"

jobs:
  sql_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
        env:
          POETRY_VERSION: 1.4.2

      - name: Install dependencies
        env:
          POETRY_VIRTUALENV_IN_PROJECT: 1
        run: |
          poetry env use 3.11.3
          poetry install

      - name: Lint using SQLFluff
        run: |
          source $(poetry env info --path)/bin/activate
          
          sqlfluff lint --config=.sqlfluff
